# Generated by Django 5.2.5 on 2025-09-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_is_featured_product_sold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Sold',
            new_name='sold',
        ),
    ]
